### ISSUE TITLE
inputPath of customPages must be absolute

### ISSUE THREAD

**Issue by saintsalo** [OpenSaasAU/keystone-nextjs-auth#226]
I'm having an issue running the keystone-nextjs-auth backend locally with an error on inputPaths for custom pages. 
I don't see much information on the keystone js docs for getAdditionalFiles ui property, but that seems to be the issue. 

After running `yarn dev:backend`, i'm left with this error:

```
🚨 There was an error loading your Keystone config
Error: An inputPath of "../../customPages/signin.js" was provided to copy but inputPaths must be absolute
    at writeAdminFile (/Users/salo/Code/examples/keystone-nextjs-auth/node_modules/@keystone-6/core/dist/initConfig-c6b5cfcb.cjs.dev.js:557:13)
    at /Users/salo/Code/examples/keystone-nextjs-auth/node_modules/@keystone-6/core/dist/initConfig-c6b5cfcb.cjs.dev.js:604:69
    at Array.map (<anonymous>)
    at Object.generateAdminUI (/Users/salo/Code/examples/keystone-nextjs-auth/node_modules/@keystone-6/core/dist/initConfig-c6b5cfcb.cjs.dev.js:604:57)
    at initKeystone (/Users/salo/Code/examples/keystone-nextjs-auth/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:265:11)
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error invalid json response body at http://localhost:3000/api/auth/session reason: Unexpected token < in JSON at position 0 {
  error: {
    message: 'invalid json response body at http://localhost:3000/api/auth/session reason: Unexpected token < in JSON at position 0',
    stack: 'FetchError: invalid json response body at http://localhost:3000/api/auth/session reason: Unexpected token < in JSON at position 0\n' +
      '    at /Users/salo/Code/examples/keystone-nextjs-auth/node_modules/next/dist/compiled/node-fetch/index.js:1:49606\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
    name: 'FetchError'
  },
  url: 'http://localhost:3000/api/auth/session',
  message: 'invalid json response body at http://localhost:3000/api/auth/session reason: Unexpected token < in JSON at position 0'
}
```

it seems to complain about  the relative path on `inputPath` in keystone.ts:

```
ui: {
      isAccessAllowed: (context: KeystoneContext) => !!context.session?.data,
      publicPages: ['/admin/auth/signin', '/admin/auth/error'],
      getAdditionalFiles: [
        async () => [
          {
            mode: 'copy',
            inputPath: Path.join(__dirname, './customPages/signin.js'),
            outputPath: 'pages/auth/signin.js',
          },
          {
            mode: 'copy',
            inputPath: Path.join(__dirname, './customPages/error.js'),
            outputPath: 'pages/auth/error.js',
          },
        ],
      ],
    },
```

I tried several changes to that path (and tried using `write` instead of copy with putting the src directly in keystone.ts), but still not getting it to run. 
Any ideas on how to fix that? 

Thanks!

**Comment by borisno2** [comment]
Hey @saintsalo 
I have just updated to use `Path.resolve` here that should resolve this.
Let me know if you still have any issues.
